### ISSUE TITLE
Come si imposta poi il server DHCP per tutti gli altri?

### ISSUE THREAD

**Issue by Porkechebure** [mvimercati/vps-no-dhcp#2]
Ciao,
Va bene la procedura, ma poi tutti gli altri dispositivi come lo prendono l'ip se la vodafone station non glielo serve?
Occorre impostare singolamente per ognuno un server DHCP? Perchè se uno lo può impostare nel router allora il server DHCP viene chiamato e assegna gli ip, ma se la vodafone station ce l'ha disattivato, come fanno i vari device a trovare un server DHCP in autonomia?
Ho un pi-hole già pronto, ma come fanno a capire i vari device che al posto del defunto DHCP della vodafone station devono usare pi-hole?

**Comment by mvimercati** [comment]
Ciao, lo scopo della guida è proprio quello di disattivare il DHCP della vodafone station, perché in alcuni casi può essere utile. Primo fra tutti è il caso in cui uno voglia utilizzare un proprio DHCP, e non quello integrato nel router. Infatti è un problema avere due dhcp attivi nella stessa sottorete...anche abbastanza subdolo, perché magari inizialmente sembra funzionare ma poi non sempre i device riescono ad acquisire l'indirizzo dal DHCP. Alternativamente può esistere anche una rete senza alcun DHCP, ma gli indirizzi dei vari device dovranno essere impostati a mano, uno per uno. Non è tanto comodo.
PI-Hole ha anche lui un server dhcp (attivabile opzionalmente), oltre ad essere notoriamente un server DNS.
Per i device usare un DHCP piuttosto che un altro, premesso che il tutto sia configurato correttamente sul server stesso, è del tutto trasparente. Infatti DHCP funziona con messaggi di tipo broadcast, ovvero ogni device chiede a tutta la rete che gli sia assegnato un indirizzo (più netmask, più gateway) e il DHCP in ascolto gli risponde direttamente. Se vuoi approfondire sicuramente trovi delle guide online.....

**Comment by Porkechebure** [comment]
Ciao,
Ho scoperto quanto dici cercando e documentandomi. La guida funziona ed effettivamente il broadcast è partito e il pi-hole assegna correttamente gli ip (mentre per ipv6 mi genera alcuni errori).

Dato che sei con vodafone, da quanto mi pare di capire posso chiederti un'altra cosa?
A me non ne vuole proprio sapere di funzionare, serve solo google, telegram e reddit, e dopo pochi minuti che il pihole cattura qualche request, inizia poi a non servire proprio niente. Tutto internet è fuori uso e devo rimettere il dns vecchio.

Mi sai dire se c'è qualche blocco di DNS rebinding o altro per vodafone o sto sbagliando qualcosa?
